version: "3.9"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  api:
    build:
      context: ./app       # Path to folder containing Dockerfile
      dockerfile: Dockerfile  # Optional if named 'Dockerfile'
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./app:/app
